//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saglikveri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ayarlar
    {
        public int ayarlarid { get; set; }
        public string Siteadi { get; set; }
        public string Sitemail { get; set; }
        public string Smtp { get; set; }
        public string port { get; set; }
        public string ayarlarsifre { get; set; }
        public System.DateTime ayarlartarih { get; set; }
        public int kullanicid { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
