//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saglikveri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bloglar
    {
        public Bloglar()
        {
            this.Yaptims = new HashSet<Yaptim>();
        }
    
        public int blogid { get; set; }
        public string blogAdi { get; set; }
        public string blogUrl { get; set; }
        public string blogAcilama { get; set; }
        public string blogKeyword { get; set; }
        public string bloResim { get; set; }
        public string blogYazi { get; set; }
        public bool blogaktif { get; set; }
        public System.DateTime blogTarih { get; set; }
        public int kullanicid { get; set; }
        public int kategorid { get; set; }
        public int blogGosterim { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual ICollection<Yaptim> Yaptims { get; set; }
    }
}
