//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saglikveri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori
    {
        public Kategori()
        {
            this.Bloglars = new HashSet<Bloglar>();
        }
    
        public int kategorid { get; set; }
        public string kategoriAdi { get; set; }
        public string KategoriUrl { get; set; }
        public bool KategoriAktif { get; set; }
        public System.DateTime Kategoritarih { get; set; }
        public int kullanicid { get; set; }
    
        public virtual ICollection<Bloglar> Bloglars { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
