//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saglikveri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public Kullanici()
        {
            this.Ayarlars = new HashSet<Ayarlar>();
            this.Bloglars = new HashSet<Bloglar>();
            this.Kategoris = new HashSet<Kategori>();
            this.sagliktabloes = new HashSet<sagliktablo>();
            this.Yaptims = new HashSet<Yaptim>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int kullanicid { get; set; }
        public string kullaniciadi { get; set; }
        public string kullaniciadisoyadi { get; set; }
        public string kullaniciemail { get; set; }
        public System.DateTime kullanicitarih { get; set; }
        public string kullaniciSifre { get; set; }
        public string KullaniciSifretekrar { get; set; }
        public string KullaniciEskiSifre { get; set; }
        public bool KullaniciAktifMi { get; set; }
        public string KullaniciUrl { get; set; }
    
        public virtual ICollection<Ayarlar> Ayarlars { get; set; }
        public virtual ICollection<Bloglar> Bloglars { get; set; }
        public virtual ICollection<Kategori> Kategoris { get; set; }
        public virtual ICollection<sagliktablo> sagliktabloes { get; set; }
        public virtual ICollection<Yaptim> Yaptims { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
