//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saglikveri
{
    using System;
    using System.Collections.Generic;
    
    public partial class sagliktablo
    {
        public int saglikid { get; set; }
        public int kullanicid { get; set; }
        public string saglikAdi { get; set; }
        public string saglikAciklama { get; set; }
        public string saglikKeyword { get; set; }
        public string saglikResim { get; set; }
        public string SaglikYazi { get; set; }
        public bool Saglikaktif { get; set; }
        public System.DateTime saglikTarih { get; set; }
        public int SaglikGosterim { get; set; }
        public string saglikUrl { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
